### ISSUE TITLE
Trouble setting for option on wait.until

### ISSUE THREAD

**Issue by underbluewaters** [jgonera/webspecter#3]
I'm having trouble setting the timeout option when calling wait.until within a helper. The test I'm attempting to run always time's out in 1 second regardless of what I set the for: option to. 

I created a gist with my exact code:
https://gist.github.com/4020506

I'd assumed I was having some issues with scope and coffeescript's magic since there are a lot of functions being passed around... but I just can't pin it down.

Thanks

**Comment by jgonera** [comment]
Closing the issue before archiving the repo.
