### ISSUE TITLE
Add support of running webspecter in node spawn process

### ISSUE THREAD

**Issue by raykin** [jgonera/webspecter#8]
It's not possible to run webspecter in node process

``` coffee-script
testing = (app_pid)->
  options = ['test']
  cmd = which.sync 'webspecter'
  testing = spawn cmd, options
  # not worked. cause phantomjs didnt support running with Node
  testing.stdout.pipe process.stdout
  testing.stderr.pipe process.stderr
  testing.on 'exit', (status) -> process.kill(app_pid)
```

it failed with the string "Unable to open file '/dev/stdout'" was thrown, throw an Error :).
Here is a good link about it  https://groups.google.com/forum/?fromgroups=#!topic/phantomjs/2rFv57riMR4

**Comment by jgonera** [comment]
Closing the issue before archiving the repo.
